name: amazonlinux2-apache24-php74
on:
#  pull_request:
#    branches: [master]
  workflow_dispatch:
    branches: [master]
jobs:
  publish:
    name: Push Docker image to GitHub Container Registry
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: webserver-amzn2
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}
      - name: Push to GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:apache24-php74
          file: amazonlinux2-apache24-php74/Dockerfile
        env:
          DOCKER_BUILDKIT: 1
