name: amazonlinux-2023
on:
#  pull_request:
#    branches: [master]
  workflow_dispatch:
    branches: [master]
jobs:
  publish:
    name: Push Docker image to GitHub Container Registry
    runs-on: ubuntu-latest
    env:
      PACKAGE_NAME: amazonlinux
      VERSION_NAME: 2023
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Push to GitHub Container Registry
        uses: docker/build-push-action@v5
        with:
          provenance: false
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ env.PACKAGE_NAME }}:${{ env.VERSION_NAME }}
            ghcr.io/${{ github.repository_owner }}/${{ env.PACKAGE_NAME }}:latest
          file: ${{ env.PACKAGE_NAME }}/${{ env.VERSION_NAME }}/Dockerfile
          platforms: linux/amd64, linux/arm64/v8
