name: webserver-centos83-apache24-php81
on:
#  pull_request:
#    branches: [master]
  workflow_dispatch:
    branches: [master]
jobs:
  publish:
    name: Push Docker image to GitHub Container Registry
    runs-on: ubuntu-latest
    env:
      PACKAGE_NAME: webserver-centos83
      VERSION_NAME: apache24-php81
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up docker qemu
        uses: docker/setup-qemu-action@v1
      - name: Set up docuker buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}
      - name: Push to GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ env.PACKAGE_NAME }}:${{ env.VERSION_NAME }}
          file: ${{ env.PACKAGE_NAME }}/${{ env.VERSION_NAME }}/Dockerfile
          platforms: linux/amd64, linux/arm64
        env:
          DOCKER_BUILDKIT: 1
